const alarmsData = [
    {
        id: 1,
        text: 'One',
        isCompleted: true,
        isToday: true,
        hour: '10:00',
        isAlert: true,
    },
    {
        id: 2,
        text: 'Two',
        isCompleted: false,
        isToday: false,
        hour: '11:00',
        isAlert: true,
    },
    {
        id: 3,
        text: 'Three',
        isCompleted: true,
        isToday: true,
        hour: '12:00',
        isAlert: false,
    },
    {
        id: 4,
        text: 'Four',
        isCompleted: false,
        isToday: true,
        hour: '13:00',
        isAlert: false,
    },
    {
        id: 5,
        text: 'Five',
        isCompleted: false,
        isToday: true,
        hour: '14:00',
        isAlert: false,
    },
    {
        id: 6,
        text: 'Six',
        isCompleted: false,
        isToday: false,
        hour: '15:00',
        isAlert: false,
    },
    {
        id: 7,
        text: 'Seven',
        isCompleted: false,
        isToday: true,
        hour: '16:00',
        isAlert: false,
    },
    {
        id: 8,
        text: 'Eight',
        isCompleted: false,
        isToday: false,
        hour: '17:00',
        isAlert: false,
    },
    {
        id: 9,
        text: 'Nine',
        isCompleted: false,
        isToday: false,
        hour: '18:00',
        isAlert: false,
    }
];

module.exports = { alarmsData };